from dataclasses import dataclass, field

from analyzer.findings import Finding
from generator.testcase import TestCase
from models.analysis_result import AnalysisResult


@dataclass
class EdgeForgeReport:
    """
    Final report generated by EdgeForge.
    """

    analysis: AnalysisResult

    findings: list[Finding] = field(default_factory=list)

    test_cases: list[TestCase] = field(default_factory=list)

    summary: dict = field(default_factory=dict)